[#IC-436]  Add retry to service, message and messagestatus
pagopa/io-functions-elt pull request #51
Opened 2022-05-12 11:06 UTC by fabriziopapi

The current data stream towards PDND store errors without reprocessing it. With this implementation, the errors will be published in a storage queue and re-processed with a trigger (a queue/trigger for each stream).   

#### List of Changes

replace error table storage with a queue for services, messages and message-status
add re-processing trigger for error queues
add missing unit tests

#### Motivation and Context

mitigate the pdnd missing data risk

#### How Has This Been Tested?

unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-12 11:34 UTC, fabriziopapi commented
depends on https://github.com/pagopa/io-infra/pull/172

2022-05-23 14:23 UTC, AleDore commented on CosmosApiMessagesChangeFeed/handler.ts
> +  errorQueueClient?: QueueClient
why nullable?

2022-05-23 14:23 UTC, AleDore commented on CosmosApiMessagesFailure/handler.ts
> +      lefts: T.of(retrievedMessages.filter(m => E.isLeft(m))),
```suggestion
      lefts: T.of(retrievedMessages.filter(E.isLeft)),
```

2022-05-23 14:23 UTC, AleDore commented on CosmosApiMessagesFailure/handler.ts
> +      lefts: T.of(retrievedMessages.filter(m => E.isLeft(m))),
or RA.lefts?

2022-05-23 14:23 UTC, AleDore commented on CosmosApiMessagesFailure/handler.ts
> +        T.map(RA.map(m => E.right(m)))
```suggestion
        T.map(RA.rights)
```

2022-06-06 08:28 UTC, gquadrati requested changes
I tried it, error handling queues are not working

2022-12-19 09:18 UTC, closed without merging